"use client";

import { useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, BadgeCheck, BellRing, Building2, CalendarCheck, CalendarClock, CheckCircle2, CircleGauge, LockKeyhole, MapPin, RotateCcw, UsersRound } from "lucide-react";
import { useScheduling } from "@tau/scheduling";
import { Badge } from "@tau/ui/badge";
import { Button } from "@tau/ui/button";
import { Progress } from "@tau/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@tau/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@tau/ui/tabs";
import { PageHeader } from "@/components/console/page-header";
import { Section } from "@/components/console/section";

const scheduler = { personId: "staff-scheduler", name: "Mrs. Grace Ojo", role: "Central Scheduler" };

export default function SchedulingPage() {
  const { calendars, calendarNotifications, campuses, rooms, maintenanceBlocks, activities, conflicts, workloads, utilisation, changeNotices, mutations } = useScheduling();
  const [message, setMessage] = useState<string>();
  const calendar = calendars[0];
  const unresolvedHard = conflicts.filter((item) => item.severity === "Hard" && !item.resolved);
  const usedHours = utilisation.reduce((sum, item) => sum + item.usedHours, 0);
  const reservedHours = utilisation.reduce((sum, item) => sum + item.reservedHours, 0);

  function announce(result: { ok: boolean; error?: string }, success: string) { setMessage(result.ok ? success : result.error); }

  return <div className="space-y-6">
    <PageHeader eyebrow="EP-11 · Scheduling operations" title="Calendar, timetable, rooms and workload" description="Coordinate teaching and examinations with visible ownership, explainable constraints and publication controls." actions={<div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => mutations.reset()}><RotateCcw className="mr-1.5 size-3.5" />Reset demo</Button><Button asChild size="sm"><Link href="/scheduling/my-timetable"><CalendarClock className="mr-1.5 size-3.5" />My timetable</Link></Button></div>} />
    {message && <div role="status" className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm font-medium">{message}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric icon={CalendarCheck} label="Academic calendar" value={`v${calendar?.version ?? "—"}`} detail={calendar ? `${calendar.status} · ${calendar.authority}` : "Not configured"} />
      <Metric icon={AlertTriangle} label="Hard conflicts" value={String(unresolvedHard.length)} detail="Must clear before release" danger={unresolvedHard.length > 0} />
      <Metric icon={CircleGauge} label="Room activity" value={`${usedHours}h used`} detail={`${reservedHours}h currently reserved`} />
      <Metric icon={UsersRound} label="Workload exceptions" value={String(workloads.filter((item) => Math.abs(item.variance) > 12).length)} detail="Outside ±12 configured hours" />
    </div>

    <Tabs defaultValue="calendar"><TabsList className="max-w-full justify-start overflow-x-auto"><TabsTrigger value="calendar">Academic calendar</TabsTrigger><TabsTrigger value="timetable">Timetable & conflicts</TabsTrigger><TabsTrigger value="rooms">Rooms & facilities</TabsTrigger><TabsTrigger value="workload">Workload</TabsTrigger></TabsList>
      <TabsContent value="calendar" className="space-y-6">
        <div className="grid gap-6 xl:grid-cols-[1fr_0.7fr]">
          <Section title={calendar?.title ?? "Academic calendar"} description="Approved publication identity and milestone ownership">
            {calendar && <><div className="grid gap-4 rounded-xl bg-muted/40 p-4 sm:grid-cols-3"><Fact label="Version" value={`Version ${calendar.version}`} /><Fact label="Status" value={calendar.status} /><Fact label="Authority" value={calendar.authority} /></div><div className="mt-5 divide-y">{calendar.milestones.map((milestone) => <div key={milestone.id} className="flex gap-3 py-3"><CalendarClock className="mt-0.5 size-4 shrink-0 text-primary" /><div><div className="text-sm font-semibold">{milestone.name}</div><div className="mt-1 text-xs text-muted-foreground">{formatDate(milestone.startsAt)}{milestone.endsAt ? ` → ${formatDate(milestone.endsAt)}` : ""} · {milestone.audience.join(", ")}</div></div></div>)}</div>{calendar.status === "Approved" && <Button className="mt-5" onClick={() => announce(mutations.publishCalendar(calendar.id, scheduler), "Approved calendar published; affected audiences queued for notification.")}><BellRing className="mr-2 size-4" />Publish and notify</Button>}</>}
          </Section>
          <Section title="Revision history" description="Every version retains authority and rationale"><div className="space-y-3">{calendar?.revisions.slice().reverse().map((revision) => <div key={`${revision.version}-${revision.status}`} className="rounded-lg border p-3"><div className="flex items-center justify-between"><strong className="text-sm">Version {revision.version}</strong><Badge variant="outline">{revision.status}</Badge></div><div className="mt-2 text-xs text-muted-foreground">{revision.authority}<br />{revision.changedBy} · {formatDate(revision.changedAt)}</div><p className="mt-2 text-xs">{revision.reason}</p></div>)}</div>{calendarNotifications.length > 0 && <div className="mt-4 rounded-lg bg-emerald-500/10 p-3 text-xs text-emerald-800 dark:text-emerald-200"><BadgeCheck className="mr-1.5 inline size-4" />{calendarNotifications.length} audience notification(s) queued.</div>}</Section>
        </div>
      </TabsContent>

      <TabsContent value="timetable" className="space-y-6">
        {unresolvedHard.length > 0 && <div className="rounded-xl border border-destructive/25 bg-destructive/5 p-4"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 size-5 text-destructive" /><div><h2 className="font-bold">Release blocked</h2><p className="mt-1 text-sm text-muted-foreground">{unresolvedHard.length} unresolved hard conflict(s) must be corrected or explicitly overridden before publication.</p></div></div></div>}
        <Section title="Teaching and examination schedule" description="Approved assignments expose their academic owner and validation state"><Table><TableHeader><TableRow><TableHead>Activity</TableHead><TableHead>Time</TableHead><TableHead>Room</TableHead><TableHead>People</TableHead><TableHead>Owner</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{activities.map((item) => { const room = rooms.find((candidate) => candidate.id === item.roomId); const itemConflicts = conflicts.filter((conflict) => conflict.activityIds.includes(item.id) && !conflict.resolved); return <TableRow key={item.id}><TableCell><div className="font-semibold">{item.code}</div><div className="text-xs text-muted-foreground">{item.title} · {item.kind}</div></TableCell><TableCell className="text-xs">{formatTimeRange(item.startsAt, item.endsAt)}</TableCell><TableCell><div className="text-sm font-medium">{room?.code}</div><div className="text-xs text-muted-foreground">{campuses.find((campus) => campus.id === item.campusId)?.name}</div></TableCell><TableCell className="text-xs">{item.staffNames.join(", ")}<br /><span className="text-muted-foreground">{item.cohortNames.join(", ")}</span></TableCell><TableCell className="text-xs">{item.ownershipUnit}<br /><span className="text-muted-foreground">{item.ownerName}</span></TableCell><TableCell><Badge variant="outline">{item.status}</Badge>{itemConflicts.length > 0 && <div className="mt-1 text-xs font-semibold text-destructive">{itemConflicts.length} conflict(s)</div>}{item.override && <div className="mt-1 text-xs text-amber-700">Override: {item.override.reason}</div>}</TableCell><TableCell><div className="flex justify-end gap-1.5">{item.status === "Draft" && <Button size="sm" variant="outline" onClick={() => announce(mutations.approveActivity(item.id), "Assignment approved; publication checks recalculated.")}>Approve</Button>}{item.id === "activity-csc205" && !item.override && <><Button size="sm" variant="outline" onClick={() => announce(mutations.assignRoom(item.id, item.roomId, scheduler), "Room assigned.")}>Validate room</Button><Button size="sm" variant="outline" onClick={() => announce(mutations.assignRoom(item.id, item.roomId, scheduler, "Essential laboratory retained with Facilities-approved isolation plan."), "Constraint explicitly overridden with reason and approver.")}>Override</Button></>}{item.id === "activity-mth201" && item.status !== "Cancelled" && <Button size="sm" variant="outline" onClick={() => announce(mutations.cancelActivity(item.id), "Conflicting assignment cancelled; utilization updated.")}>Cancel clash</Button>}</div></TableCell></TableRow>; })}</TableBody></Table><div className="mt-4 flex justify-end"><Button onClick={() => announce(mutations.publishTimetable(), "Conflict-free approved timetable published to portal and feed.")}>Run checks and publish</Button></div></Section>
        <Section title="Conflict register" description="Student, staff, room, campus and facilities checks run before every release"><div className="grid gap-3 md:grid-cols-2">{conflicts.map((conflict) => <div key={conflict.id} className={`rounded-lg border p-3 ${conflict.resolved ? "opacity-60" : "border-destructive/30"}`}><div className="flex items-center justify-between"><Badge variant="outline">{conflict.type.replaceAll("_", " ")}</Badge><span className="text-xs font-bold">{conflict.resolved ? "Resolved by override" : `${conflict.severity} conflict`}</span></div><p className="mt-2 text-sm">{conflict.description}</p></div>)}</div></Section>
      </TabsContent>

      <TabsContent value="rooms" className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rooms.map((room) => { const usage = utilisation.find((item) => item.roomId === room.id); const block = maintenanceBlocks.find((item) => item.roomId === room.id && item.status !== "Cancelled"); return <article key={room.id} className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><Building2 className="size-4" /></span><Badge variant="outline">{room.code}</Badge></div><h3 className="mt-4 font-bold">{room.name}</h3><p className="mt-1 text-xs text-muted-foreground"><MapPin className="mr-1 inline size-3" />{campuses.find((item) => item.id === room.campusId)?.name} · {room.capacity} seats</p><div className="mt-3 text-xs"><strong>Equipment:</strong> {room.equipment.join(", ")}<br /><strong>Access:</strong> {room.accessibility.join(", ")}</div>{block && <div className="mt-3 rounded-lg bg-amber-500/10 p-2 text-xs text-amber-900 dark:text-amber-200"><strong>Maintenance block</strong><br />{formatTimeRange(block.startsAt, block.endsAt)}<br />{block.reason} · Owner: {block.owner}</div>}<div className="mt-4 grid grid-cols-3 gap-1 text-center text-xs"><Usage label="Reserved" value={usage?.reservedHours ?? 0} /><Usage label="Used" value={usage?.usedHours ?? 0} /><Usage label="Cancelled" value={usage?.cancelledHours ?? 0} /></div></article>; })}</div></TabsContent>

      <TabsContent value="workload"><Section title="Teaching and supervision workload" description={`Derived from approved assignments using ${workloads.length ? workloads[0].explanation.at(-1)?.replace("Rule: ", "") : "the active rule"}`}><div className="grid gap-4 lg:grid-cols-3">{workloads.map((workload) => { const percentage = Math.min(100, Math.round((workload.totalHours / workload.targetHours) * 100)); return <article key={workload.staffId} className="rounded-xl border p-4"><div className="flex items-center justify-between"><div><h3 className="font-bold">{workload.staffName}</h3><p className="text-xs text-muted-foreground">{workload.staffId}</p></div><Badge variant="outline">{workload.variance > 0 ? `+${workload.variance}` : workload.variance}h</Badge></div><div className="mt-4 flex items-end justify-between"><span className="text-2xl font-bold">{workload.totalHours}h</span><span className="text-xs text-muted-foreground">Target {workload.targetHours}h</span></div><Progress className="mt-2" value={percentage} /><div className="mt-4 space-y-1 text-xs text-muted-foreground">{workload.explanation.map((line) => <div key={line}><CheckCircle2 className="mr-1 inline size-3 text-emerald-600" />{line}</div>)}</div></article>; })}</div></Section></TabsContent>
    </Tabs>
    {changeNotices.length > 0 && <Link href="/scheduling/my-timetable" className="flex items-center justify-between rounded-xl border bg-card p-4 text-sm font-semibold hover:bg-muted/40"><span className="flex items-center gap-2"><Activity className="size-4 text-primary" />{changeNotices.length} timetable change alert(s) published consistently to portal and calendar feed.</span><ArrowRight className="size-4" /></Link>}
  </div>;
}

function Metric({ icon: Icon, label, value, detail, danger = false }: { icon: typeof CalendarCheck; label: string; value: string; detail: string; danger?: boolean }) { return <div className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between text-xs font-medium text-muted-foreground"><span>{label}</span><Icon className={`size-4 ${danger ? "text-destructive" : "text-primary"}`} /></div><div className={`mt-2 text-2xl font-bold ${danger ? "text-destructive" : ""}`}>{value}</div><div className="mt-1 line-clamp-2 text-xs text-muted-foreground">{detail}</div></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>; }
function Usage({ label, value }: { label: string; value: number }) { return <div className="rounded bg-muted/50 p-2"><strong>{value}h</strong><div className="text-[0.65rem] text-muted-foreground">{label}</div></div>; }
function formatDate(value: string) { return new Date(value).toLocaleDateString(undefined, { dateStyle: "medium" }); }
function formatTimeRange(start: string, end: string) { const date = new Date(start).toLocaleDateString(undefined, { month: "short", day: "numeric" }); const from = new Date(start).toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" }); const to = new Date(end).toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" }); return `${date} · ${from}–${to}`; }
