import type {
  AcademicSession,
  ConfigurationActivity,
  FeatureFlag,
  OrganisationUnit,
  PolicyRule,
  ReferenceCategory,
} from "./types";

const history = (version: string, effectiveFrom: string, reason: string) => [
  {
    version,
    status: "Published" as const,
    effectiveFrom,
    changedAt: "02 Sep 2026, 17:22",
    changedBy: "Chinedu Okafor",
    reason,
  },
];

export const initialOrganisationUnits: OrganisationUnit[] = [
  { id: "UNISITE-UNI-001", name: "UniSite", shortName: "UniSite", type: "University", campus: "University-wide", head: "Prof. Adaeze Nwosu", email: "vc@unisite.edu.ng", effectiveFrom: "2022-08-01", status: "Active", reason: "Institutional establishment", authority: "University Charter 2022", history: history("v1.0", "2022-08-01", "Institution established") },
  { id: "UNISITE-CMP-001", name: "Main Campus, Umuchukwu", shortName: "Main Campus", type: "Campus", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Dr. Emeka Udeh", email: "campus@unisite.edu.ng", effectiveFrom: "2022-08-01", status: "Active", reason: "Principal campus", authority: "University Charter 2022", history: history("v1.0", "2022-08-01", "Campus established") },
  { id: "UNISITE-FAC-001", name: "Faculty of Medicine", shortName: "Medicine", type: "Faculty", parentId: "UNISITE-UNI-001", reportingUnitId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Prof. Ifeanyi Okoli", email: "medicine@unisite.edu.ng", effectiveFrom: "2022-08-01", status: "Active", reason: "Founding faculty", authority: "Senate resolution 22/004", history: history("v2.1", "2022-08-01", "Reporting line confirmed") },
  { id: "UNISITE-DEP-001", name: "Department of Anatomy", shortName: "Anatomy", type: "Department", parentId: "UNISITE-FAC-001", reportingUnitId: "UNISITE-FAC-001", campus: "Umuchukwu", head: "Dr. Amaka Eze", email: "anatomy@unisite.edu.ng", effectiveFrom: "2023-01-09", status: "Active", reason: "Academic delivery", authority: "Senate resolution 22/104", history: history("v1.2", "2023-01-09", "Head of unit updated") },
  { id: "UNISITE-DEP-002", name: "Department of Physiology", shortName: "Physiology", type: "Department", parentId: "UNISITE-FAC-001", reportingUnitId: "UNISITE-FAC-001", campus: "Umuchukwu", head: "Dr. Chuka Obi", email: "physiology@unisite.edu.ng", effectiveFrom: "2023-01-09", status: "Active", reason: "Academic delivery", authority: "Senate resolution 22/104", history: history("v1.0", "2023-01-09", "Department established") },
  { id: "UNISITE-FAC-002", name: "Faculty of Dentistry", shortName: "Dentistry", type: "Faculty", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Prof. Hauwa Bello", email: "dentistry@unisite.edu.ng", effectiveFrom: "2023-01-09", status: "Active", reason: "Programme expansion", authority: "Senate resolution 22/118", history: history("v1.0", "2023-01-09", "Faculty established") },
  { id: "UNISITE-FAC-003", name: "Faculty of Nursing and Health Sciences", shortName: "Nursing & Health", type: "Faculty", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Prof. Grace Adeyemi", email: "nursing@unisite.edu.ng", effectiveFrom: "2023-01-09", status: "Active", reason: "Programme expansion", authority: "Senate resolution 22/119", history: history("v1.0", "2023-01-09", "Faculty established") },
  { id: "UNISITE-FAC-004", name: "Faculty of Pharmacy", shortName: "Pharmacy", type: "Faculty", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Prof. Tunde Salako", email: "pharmacy@unisite.edu.ng", effectiveFrom: "2024-01-08", status: "Active", reason: "Programme expansion", authority: "Senate resolution 23/083", history: history("v1.0", "2024-01-08", "Faculty established") },
  { id: "UNISITE-FAC-005", name: "Faculty of Public Health", shortName: "Public Health", type: "Faculty", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Dr. Nkiru Nnaji", email: "publichealth@unisite.edu.ng", effectiveFrom: "2024-01-08", status: "Active", reason: "Programme expansion", authority: "Senate resolution 23/084", history: history("v1.0", "2024-01-08", "Faculty established") },
  { id: "UNISITE-FAC-006", name: "Faculty of Biomedical Sciences", shortName: "Biomedical Sciences", type: "Faculty", parentId: "UNISITE-UNI-001", campus: "Umuchukwu", head: "Prof. Seyi Akande", email: "biomedical@unisite.edu.ng", effectiveFrom: "2026-09-21", status: "Draft", reason: "2026/2027 expansion", authority: "Senate paper 26/114", notes: "Pending Council ratification", history: [{ version: "v0.1", status: "Draft", effectiveFrom: "2026-09-21", changedAt: "12 Sep 2026, 09:42", changedBy: "Chinedu Okafor", reason: "Initial draft" }] },
  { id: "UNISITE-DIR-001", name: "Directorate of Academic Planning", shortName: "DAP", type: "Directorate", parentId: "UNISITE-UNI-001", campus: "University-wide", head: "Dr. Ngozi Madu", email: "dap@unisite.edu.ng", effectiveFrom: "2022-08-01", status: "Active", reason: "Governance structure", authority: "University Charter 2022", history: history("v1.1", "2022-08-01", "Mandate updated") },
  { id: "UNISITE-ADM-001", name: "Quality Assurance Unit", shortName: "Quality Assurance", type: "Administrative unit", parentId: "UNISITE-DIR-001", reportingUnitId: "UNISITE-DIR-001", campus: "University-wide", head: "Mrs. Amina Yusuf", email: "quality@unisite.edu.ng", effectiveFrom: "2024-01-08", status: "Active", reason: "Quality governance", authority: "Council decision 23/041", history: history("v1.0", "2024-01-08", "Unit established") },
];

export const initialAcademicSessions: AcademicSession[] = [
  { id: "2024-2025", name: "2024/2025", start: "2024-09-23", end: "2025-07-26", status: "Archived", version: "v1.0", lastModified: "26 Jul 2025", variations: [{ id: "var-1", programme: "MBBS", deliveryMode: "Clinical rotation", change: "48-week clinical calendar" }], terms: [{ id: "t-1", name: "First Semester", start: "2024-09-23", end: "2025-02-15", teachingWeeks: 14, examWeeks: 3 }, { id: "t-2", name: "Second Semester", start: "2025-03-03", end: "2025-07-26", teachingWeeks: 14, examWeeks: 3 }], milestones: [] },
  { id: "2025-2026", name: "2025/2026", start: "2025-09-22", end: "2026-07-25", status: "Published", version: "v1.2", lastModified: "03 Sep 2026", variations: [{ id: "var-2", programme: "Master of Public Health", deliveryMode: "Weekend", change: "Teaching runs Friday–Sunday" }], terms: [{ id: "t-3", name: "First Semester", start: "2025-09-22", end: "2026-02-14", teachingWeeks: 14, examWeeks: 3 }, { id: "t-4", name: "Second Semester", start: "2026-03-02", end: "2026-07-25", teachingWeeks: 14, examWeeks: 3 }], milestones: [{ id: "m-1", name: "Course registration", type: "Registration", start: "2025-09-22", end: "2025-10-10", audience: "All students", status: "Published" }, { id: "m-2", name: "Senate results meeting", type: "Senate", start: "2026-08-20", audience: "Senate", status: "Published" }] },
  { id: "2026-2027", name: "2026/2027", start: "2026-09-21", end: "2027-07-24", status: "Draft", version: "v0.4", lastModified: "11 Sep 2026", variations: [{ id: "var-3", programme: "MBBS", deliveryMode: "Clinical rotation", change: "Rotation blocks begin two weeks early" }, { id: "var-4", programme: "Master of Public Health", deliveryMode: "Weekend", change: "Teaching runs Friday–Sunday" }], terms: [{ id: "t-5", name: "First Semester", start: "2026-09-21", end: "2027-02-13", teachingWeeks: 14, examWeeks: 3 }, { id: "t-6", name: "Second Semester", start: "2027-03-01", end: "2027-07-24", teachingWeeks: 14, examWeeks: 3 }], milestones: [{ id: "m-3", name: "New student orientation", type: "Orientation", start: "2026-09-16", end: "2026-09-18", audience: "New students", status: "Draft" }, { id: "m-4", name: "Course registration", type: "Registration", start: "2026-09-21", end: "2026-10-09", audience: "All students", status: "Draft" }, { id: "m-5", name: "Add/drop closes", type: "Deadline", start: "2026-10-16", audience: "All students", status: "Draft" }] },
];

const values = (items: [string, string, string[]][]) => items.map(([code, name, usedBy], index) => ({ id: code.toLowerCase(), code, name, sortOrder: index + 1, effectiveFrom: "2022-08-01", status: "Active" as const, usedBy }));

export const initialReferenceCategories: ReferenceCategory[] = [
  { id: "countries", name: "Countries", description: "ISO-aligned country names used across institutional records.", owner: "Registry", lastUpdate: "08 Sep 2026", version: "v3.2", usageCount: 12460, status: "Published", values: values([["NG", "Nigeria", ["Admissions", "Student records", "HR"]], ["GH", "Ghana", ["Admissions"]], ["GB", "United Kingdom", ["Admissions", "Partnerships"]]]) },
  { id: "nigerian-states", name: "Nigerian states", description: "States and the Federal Capital Territory.", owner: "Registry", lastUpdate: "14 Aug 2026", version: "v2.1", usageCount: 9873, status: "Published", values: values([["AN", "Anambra", ["Admissions", "Student records"]], ["LA", "Lagos", ["Admissions", "Student records"]], ["FCT", "Federal Capital Territory", ["Admissions"]]]) },
  { id: "lgas", name: "Local government areas", description: "LGAs grouped by Nigerian state.", owner: "Registry", lastUpdate: "19 Jul 2026", version: "v4.0", usageCount: 8642, status: "Published", values: values([["AGU", "Aguata", ["Admissions"]], ["ANA-N", "Anambra North", ["Admissions"]]]) },
  { id: "qualification-types", name: "Qualification types", description: "Recognised entry and prior-learning qualifications.", owner: "Admissions", lastUpdate: "03 Sep 2026", version: "v1.8", usageCount: 3240, status: "Published", values: values([["SSCE", "Senior School Certificate", ["Admissions"]], ["BSC", "Bachelor degree", ["Admissions", "HR"]]]) },
  { id: "document-types", name: "Document types", description: "Document classifications for records management.", owner: "Registry", lastUpdate: "01 Sep 2026", version: "v2.4", usageCount: 5431, status: "Published", values: values([["BIRTH", "Birth certificate", ["Admissions"]], ["TRANS", "Academic transcript", ["Admissions", "Student records"]]]) },
  { id: "admission-routes", name: "Admission routes", description: "University entry and transfer routes.", owner: "Admissions", lastUpdate: "28 Aug 2026", version: "v1.6", usageCount: 2140, status: "Published", values: values([["UTME", "UTME", ["Admissions"]], ["DE", "Direct entry", ["Admissions"]]]) },
  { id: "delivery-modes", name: "Delivery modes", description: "Approved programme delivery patterns.", owner: "Academic Planning", lastUpdate: "11 Sep 2026", version: "v2.0", usageCount: 94, status: "Published", values: values([["FT", "Full-time", ["Curriculum", "Timetabling"]], ["WKND", "Weekend", ["Curriculum"]]]) },
  { id: "programme-levels", name: "Programme levels", description: "Undergraduate and postgraduate level codes.", owner: "Academic Planning", lastUpdate: "24 Aug 2026", version: "v1.9", usageCount: 328, status: "Published", values: values([["UG", "Undergraduate", ["Curriculum"]], ["PG", "Postgraduate", ["Curriculum"]]]) },
  { id: "award-types", name: "Award types", description: "Degree, diploma and certificate classifications.", owner: "Senate Office", lastUpdate: "18 Aug 2026", version: "v2.2", usageCount: 164, status: "Published", values: values([["DEG", "Degree", ["Student records"]], ["DIP", "Diploma", ["Student records"]]]) },
  { id: "unit-types", name: "Unit types", description: "Types used in the institutional structure.", owner: "Academic Planning", lastUpdate: "06 Sep 2026", version: "v1.4", usageCount: 87, status: "Published", values: values([["FAC", "Faculty", ["Organisation", "Identity"]], ["DEP", "Department", ["Organisation", "Identity"]]]) },
  { id: "student-statuses", name: "Student statuses", description: "Lifecycle states for student records.", owner: "Registry", lastUpdate: "09 Sep 2026", version: "v3.1", usageCount: 12685, status: "Published", values: values([["ACTIVE", "Active", ["Student records", "LMS"]], ["LEAVE", "Leave of absence", ["Student records", "LMS"]]]) },
];

export const initialPolicyRules: PolicyRule[] = [
  { id: "grading-undergraduate", name: "Undergraduate grading scale", category: "Grading", scope: "University-wide", version: "v3.1", effectiveSession: "2025/2026", cohorts: "All undergraduate cohorts", status: "Published", owner: "Senate Office", lastModified: "02 Sep 2026", description: "Standard score bands, grade points and pass classifications.", configuration: { "Pass mark": 40, "Maximum grade point": 5, "Fail grade": "F" }, versions: history("v3.1", "2025-09-22", "Senate resolution 26/114") },
  { id: "credit-load", name: "Semester credit load", category: "Credit", scope: "Undergraduate", version: "v2.4", effectiveSession: "2026/2027", cohorts: "2023–2026 entry", status: "Approved", owner: "Academic Planning", lastModified: "10 Sep 2026", description: "Minimum, maximum and carry-over credit load controls.", configuration: { "Minimum credits": 15, "Maximum credits": 24, "Carry-over allowed": true }, versions: [{ version: "v2.4", status: "Approved", effectiveFrom: "2026-09-21", changedAt: "10 Sep 2026", changedBy: "Chinedu Okafor", reason: "Annual policy review" }] },
  { id: "academic-standing", name: "Academic standing and progression", category: "Progression", scope: "University-wide", version: "v4.0", effectiveSession: "2026/2027", cohorts: "All taught programmes", status: "In Review", owner: "Senate Office", lastModified: "11 Sep 2026", description: "GPA thresholds for good standing, probation and withdrawal.", configuration: { "Minimum GPA": 1.5, "Minimum CGPA": 2, "Probation threshold": 1.5, "Maximum study duration": 8 }, versions: [{ version: "v4.0", status: "In Review", effectiveFrom: "2026-09-21", changedAt: "11 Sep 2026", changedBy: "Chinedu Okafor", reason: "Revised probation threshold" }, ...history("v3.2", "2025-09-22", "Annual publication")] },
  { id: "programme-approval", name: "Programme change approval", category: "Approval", scope: "Academic units", version: "v1.3", effectiveSession: "2026/2027", cohorts: "Not applicable", status: "Draft", owner: "Quality Assurance", lastModified: "09 Sep 2026", description: "Maker-checker stages for curriculum changes.", configuration: { "Approval stages": 3, "Minimum approvers": 2, "Escalation period (days)": 5, "Maker-checker": true }, versions: [{ version: "v1.3", status: "Draft", effectiveFrom: "2026-09-21", changedAt: "09 Sep 2026", changedBy: "Chinedu Okafor", reason: "Workflow redesign" }] },
  { id: "degree-classification", name: "Degree classification", category: "Degree classification", scope: "Undergraduate", version: "v2.0", effectiveSession: "2025/2026", cohorts: "2021 entry onward", status: "Published", owner: "Senate Office", lastModified: "28 Aug 2025", description: "CGPA bands and honours classifications.", configuration: { "First class minimum": 4.5, "Second upper minimum": 3.5, "Pass minimum": 1 }, versions: history("v2.0", "2025-09-22", "Senate approval") },
];

export const initialFeatureFlags: FeatureFlag[] = [
  ["programme-catalogue", "New programme catalogue", "catalogue.new_experience", "Enables the redesigned programme discovery catalogue.", "Digital Experience", true, true, false, "Prospective students", "Medium", "No restrictions", ["Programme API v2"]],
  ["grading-simulation", "Revised grading simulation", "rules.grading_simulation_v2", "Enables the revised academic standing simulation.", "Academic Systems", true, true, false, "Registry administrators", "High", "DAP and Registry", ["Rule approval workflow"]],
  ["calendar-versioning", "Academic calendar versioning", "calendar.versioning", "Creates immutable published calendar revisions.", "Academic Systems", true, true, true, "All staff", "Medium", "No restrictions", []],
  ["reference-import", "Reference-data import", "reference.import_preview", "Enables browser-only import validation and preview.", "Platform Operations", true, false, false, "Configuration administrators", "High", "DAP", ["Reference validation"]],
  ["tree-editor", "Organisational tree editor", "organisation.tree_editor", "Enables reviewed hierarchy changes.", "Academic Systems", true, true, true, "Configuration administrators", "High", "DAP", ["Unit history"]],
  ["rule-approval", "Rule approval workflow", "rules.approval_workflow", "Enables maker-checker lifecycle controls.", "Academic Systems", true, true, false, "Rule owners and reviewers", "High", "Senate Office", []],
].map(([id, name, key, description, owner, development, staging, production, audience, risk, restrictions, dependencies]) => ({ id, name, key, description, owner, development, staging, production, audience, lastChanged: "11 Sep 2026", risk, restrictions, dependencies, history: history("v1.0", "2026-09-01", "Initial rollout") })) as FeatureFlag[];

export const initialActivities: ConfigurationActivity[] = [
  { id: "a1", date: "12 Sep 2026, 09:42", actor: "Chinedu Okafor", module: "Organisation", action: "Unit created", record: "Faculty of Biomedical Sciences", previous: "No record", next: "Draft unit UNISITE-FAC-006", reason: "Senate approval for 2026/2027 expansion", environment: "Production", status: "Success" },
  { id: "a2", date: "11 Sep 2026, 16:18", actor: "Ngozi Madu", module: "Academic Rules", action: "Submitted for review", record: "Academic standing and progression v4.0", previous: "Draft", next: "In Review", reason: "Ready for Senate committee review", environment: "Production", status: "Pending" },
  { id: "a3", date: "11 Sep 2026, 14:05", actor: "Chinedu Okafor", module: "Academic Calendar", action: "Deadline updated", record: "2026/2027 course registration", previous: "Ends 02 Oct 2026", next: "Ends 09 Oct 2026", reason: "Align with late admission window", environment: "Production", status: "Success" },
  { id: "a4", date: "10 Sep 2026, 11:31", actor: "Amina Yusuf", module: "Feature Flags", action: "Feature promoted", record: "Revised grading simulation", previous: "Development enabled", next: "Staging enabled", reason: "UAT cycle 2 approved", environment: "Staging", status: "Success" },
  { id: "a5", date: "09 Sep 2026, 15:20", actor: "Chinedu Okafor", module: "Reference Data", action: "Value deprecated", record: "Admission route: Direct diploma transfer", previous: "Active", next: "Scheduled for deactivation", reason: "Route retired by Admissions", environment: "Production", status: "Scheduled" },
  { id: "a6", date: "08 Sep 2026, 10:08", actor: "Amina Yusuf", module: "Feature Flags", action: "Configuration rolled back", record: "Reference-data import", previous: "Staging enabled", next: "Staging disabled", reason: "Validation defect CFG-218", environment: "Staging", status: "Warning" },
  { id: "a7", date: "03 Sep 2026, 13:55", actor: "Ngozi Madu", module: "Academic Calendar", action: "Session published", record: "2025/2026 v1.2", previous: "Approved", next: "Published", reason: "Registrar publication approval", environment: "Production", status: "Success" },
  { id: "a8", date: "02 Sep 2026, 17:22", actor: "Adaeze Nwosu", module: "Academic Rules", action: "Rule published", record: "Undergraduate grading scale v3.1", previous: "Approved", next: "Published", reason: "Senate resolution 26/114", environment: "Production", status: "Success" },
];
