/**
 * The permission catalogue.
 *
 * This is deliberately a data table rather than code branches: adding the LMS or
 * bursary module means adding rows, and the access engine, the permission matrix
 * screen and the segregation-of-duties checker all pick them up unchanged.
 */

import type { PermissionDefinition } from "../domain/permission";

export const permissionCatalogue: PermissionDefinition[] = [
  // --- Identity -----------------------------------------------------------
  {
    id: "identity:person:read",
    module: "identity",
    resource: "person",
    action: "read",
    label: "View person records",
    description: "Read directory details and the affiliations linked to a person.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:person:write",
    module: "identity",
    resource: "person",
    action: "write",
    label: "Amend person records",
    description: "Correct names, contact details and linked affiliations.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:account:disable",
    module: "identity",
    resource: "account",
    action: "disable",
    label: "Disable an account",
    description: "Suspend or disable an account, ending every live session immediately.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:role-assignment:prepare",
    module: "identity",
    resource: "role-assignment",
    action: "prepare",
    label: "Prepare a role assignment",
    description: "Draft a role grant for approval. Does not itself give anybody access.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:role-assignment:approve",
    module: "identity",
    resource: "role-assignment",
    action: "approve",
    label: "Approve a role assignment",
    description: "Make a prepared role grant effective.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:delegation:manage",
    module: "identity",
    resource: "delegation",
    action: "manage",
    label: "Manage delegations",
    description: "Create and revoke time-bounded delegations of one's own authority.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:sod-exception:request",
    module: "identity",
    resource: "sod-exception",
    action: "request",
    label: "Request a duties exception",
    description: "Ask for a documented exception to a segregation-of-duties rule.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:sod-exception:approve",
    module: "identity",
    resource: "sod-exception",
    action: "approve",
    label: "Approve a duties exception",
    description: "Authorise a segregation-of-duties exception and its compensating control.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:break-glass:request",
    module: "identity",
    resource: "break-glass",
    action: "request",
    label: "Request emergency access",
    description: "Raise a break-glass request against a named incident.",
    risk: "elevated",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:break-glass:approve",
    module: "identity",
    resource: "break-glass",
    action: "approve",
    label: "Approve emergency access",
    description: "Authorise and time-box a break-glass grant raised by somebody else.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:break-glass:review",
    module: "identity",
    resource: "break-glass",
    action: "review",
    label: "Review emergency access after use",
    description: "Close out a spent break-glass grant against what was actually done.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:audit:read",
    module: "identity",
    resource: "audit",
    action: "read",
    label: "Read the audit trail",
    description: "Search tamper-evident logs and verify the hash chain.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "identity:access-review:conduct",
    module: "identity",
    resource: "access-review",
    action: "conduct",
    label: "Conduct access review",
    description: "Confirm or withdraw standing access during a periodic review.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },

  // --- Admissions ---------------------------------------------------------
  {
    id: "admissions:application:read",
    module: "admissions",
    resource: "application",
    action: "read",
    label: "View applications",
    description: "Open applications and supporting evidence within scope.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "admissions:screening:score",
    module: "admissions",
    resource: "screening",
    action: "score",
    label: "Score screening",
    description: "Record screening attendance and scores against the published rubric.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "admissions:batch:prepare",
    module: "admissions",
    resource: "batch",
    action: "prepare",
    label: "Prepare an admission batch",
    description: "Assemble a recommended admission list for approval.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "admissions:batch:approve",
    module: "admissions",
    resource: "batch",
    action: "approve",
    label: "Approve an admission batch",
    description: "Authorise a recommended admission list so offers can be published.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "admissions:assisted:intake",
    module: "admissions",
    resource: "application",
    action: "assisted-intake",
    label: "Capture assisted walk-in intake",
    description: "Capture walk-in or offline applications on behalf of candidates with applicant consent (ADM-04).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "campus",
  },
  {
    id: "admissions:case:resolve",
    module: "admissions",
    resource: "discrepancy",
    action: "resolve",
    label: "Resolve deduplication cases",
    description: "Adjudicate suspected duplicate applications and identity discrepancies (ADM-06).",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "admissions:config:manage",
    module: "admissions",
    resource: "config",
    action: "manage",
    label: "Manage admission route configuration",
    description: "Configure admission routes, cycles, qualifications and fee schedules (ADM-02).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },

  // --- Exams and records --------------------------------------------------
  {
    id: "records:result:enter",
    module: "records",
    resource: "result",
    action: "enter",
    label: "Enter results",
    description: "Record continuous assessment and examination marks.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "records:result:approve",
    module: "records",
    resource: "result",
    action: "approve",
    label: "Approve results",
    description: "Moderate and release results on behalf of the board.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "faculty",
  },
  {
    id: "records:student-record:amend",
    module: "records",
    resource: "student-record",
    action: "amend",
    label: "Amend student records",
    description:
      "Update contact and sponsor details, raise identity corrections and propose lifecycle changes (SIS-01 to SIS-04). Does not itself change protected fields or status.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:student-record:approve",
    module: "records",
    resource: "student-record",
    action: "approve",
    label: "Approve student record changes",
    description:
      "Approve identity corrections, lifecycle events and the Registry stage of programme transfers. Reads restricted field history.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "records:hold:manage",
    module: "records",
    resource: "hold",
    action: "manage",
    label: "Manage student holds",
    description: "Place and release holds owned by the grantee's unit (SIS-05). Holds never change enrolment status.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:graduation:audit",
    module: "records",
    resource: "graduation",
    action: "audit",
    label: "Run graduation audits",
    description: "Audit graduands against the approved curriculum and results, request overrides and prepare graduand lists (GRD-01, GRD-03). Does not approve them.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:graduation:approve",
    module: "records",
    resource: "graduation",
    action: "approve",
    label: "Approve graduation overrides and graduand lists",
    description: "Approve audit overrides, clearance appeals and the Senate graduand list, which freezes it.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "records:clearance:decide",
    module: "records",
    resource: "clearance",
    action: "decide",
    label: "Decide a clearance checkpoint",
    description: "Clear or block the grantee's own unit's checkpoint in a graduand's clearance case (GRD-02). Never another unit's.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:transcript:prepare",
    module: "records",
    resource: "transcript",
    action: "prepare",
    label: "Prepare transcripts",
    description: "Generate transcripts from the approved record and manage requests, dispatch and delivery evidence (GRD-04, GRD-05). Cannot sign or seal.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:certificate:manage",
    module: "records",
    resource: "certificate",
    action: "manage",
    label: "Manage certificate stock",
    description: "Receive, print, void and release numbered certificate stock to identified collectors (GRD-06).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "records:transcript:issue",
    module: "records",
    resource: "transcript",
    action: "issue",
    label: "Issue transcripts",
    description: "Produce a sealed academic transcript or certificate.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },

  // --- Finance ------------------------------------------------------------
  {
    id: "finance:invoice:raise",
    module: "finance",
    resource: "invoice",
    action: "raise",
    label: "Raise charges",
    description: "Bill a student or sponsor against the approved fee schedule.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "finance:payment:receipt",
    module: "finance",
    resource: "payment",
    action: "receipt",
    label: "Receipt payments",
    description: "Allocate a verified payment and issue its receipt.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "finance:refund:prepare",
    module: "finance",
    resource: "refund",
    action: "prepare",
    label: "Prepare a refund",
    description: "Assemble a refund for authorisation.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "finance:refund:authorise",
    module: "finance",
    resource: "refund",
    action: "authorise",
    label: "Authorise a refund",
    description: "Release a prepared refund for payment.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },

  // --- HR -----------------------------------------------------------------
  {
    id: "hr:staff-record:read",
    module: "hr",
    resource: "staff-record",
    action: "read",
    label: "View staff records",
    description: "Read establishment and appointment details within scope.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "hr:appointment:recommend",
    module: "hr",
    resource: "appointment",
    action: "recommend",
    label: "Recommend an appointment",
    description: "Put a selection panel outcome forward for approval.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "hr:appointment:approve",
    module: "hr",
    resource: "appointment",
    action: "approve",
    label: "Approve an appointment",
    description: "Authorise an appointment or promotion.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "hr:payroll:run",
    module: "hr",
    resource: "payroll",
    action: "run",
    label: "Run payroll",
    description: "Execute an approved payroll cycle.",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },

  // --- Academics, LMS and content -----------------------------------------
  {
    id: "academics:curriculum:propose",
    module: "academics",
    resource: "curriculum",
    action: "propose",
    label: "Propose curriculum changes",
    description: "Draft programme and course changes for Senate consideration.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "academics:curriculum:review",
    module: "academics",
    resource: "curriculum",
    action: "review",
    label: "Review curriculum changes",
    description: "Conduct Faculty Board and QA technical evaluations of curriculum proposals.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "academics:curriculum:approve",
    module: "academics",
    resource: "curriculum",
    action: "approve",
    label: "Approve curriculum changes",
    description: "DAP and Senate authority that authorises changes to the official curriculum catalogue.",
    risk: "elevated",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "academics:timetable:publish",
    module: "academics",
    resource: "timetable",
    action: "publish",
    label: "Publish timetables",
    description: "Release teaching and examination timetables within scope.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "faculty",
  },
  {
    id: "academics:offering:manage",
    module: "academics",
    resource: "offering",
    action: "manage",
    label: "Manage course offerings",
    description: "Create and publish semester course offerings within validated room/online and staff capacity constraints.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "academics:registration:advise",
    module: "academics",
    resource: "registration",
    action: "advise",
    label: "Advise on registration",
    description: "Review registration exceptions and academic risk for assigned advisees, and decide late-change, credit-limit, prerequisite-waiver and capacity-override requests.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "records:registration:freeze",
    module: "records",
    resource: "registration",
    action: "freeze",
    label: "Freeze registration statements",
    description: "Freeze a term's approved registration into a versioned statement, and record later amendments without rewriting the original.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:course:teach",
    module: "lms",
    resource: "course",
    action: "teach",
    label: "Teach a course",
    description: "Manage content, activities and feedback for assigned classes.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:enrolment:read",
    module: "lms",
    resource: "enrolment",
    action: "read",
    label: "View class lists",
    description: "See who is enrolled on assigned classes.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:course:design",
    module: "lms",
    resource: "course",
    action: "design",
    label: "Design course templates",
    description: "Maintain reusable course templates and build course shells from approved course versions (LMS-02).",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:discussion:moderate",
    module: "lms",
    resource: "discussion",
    action: "moderate",
    label: "Moderate course discussions",
    description: "Approve or hide discussion posts in assigned classes, with a recorded reason (LMS-04).",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:grade:finalise",
    module: "lms",
    resource: "grade",
    action: "finalise",
    label: "Finalise coursework grades",
    description:
      "Confirm moderated coursework outcomes so they can be passed back to the SIS result workflow (LMS-06). Never the marker's own grades.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:integration:request",
    module: "lms",
    resource: "integration",
    action: "request",
    label: "Propose a learning-tool integration",
    description: "Register an LTI, OneRoster or QTI integration with its data contract. Does not activate it.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:integration:approve",
    module: "lms",
    resource: "integration",
    action: "approve",
    label: "Security-review and activate integrations",
    description: "Record the security review and activate or suspend a learning-tool integration (LMS-07).",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:engagement:respond",
    module: "lms",
    resource: "engagement",
    action: "respond",
    label: "Respond to engagement alerts",
    description: "Acknowledge and resolve transparent engagement alerts routed from online-learner activity. Never changes academic standing (ODL-02).",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:caseload:export",
    module: "lms",
    resource: "caseload",
    action: "export",
    label: "Export a tutor caseload",
    description: "Export a tutor's own caseload of assigned learners for offline follow-up (ODL-03).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:integrity:configure",
    module: "lms",
    resource: "integrity",
    action: "configure",
    label: "Configure assessment integrity controls",
    description: "Choose identity and integrity controls proportionate to an assessment's risk level (ODL-04).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "department",
  },
  {
    id: "lms:integrity:dpia-approve",
    module: "lms",
    resource: "integrity",
    action: "dpia-approve",
    label: "Approve a proctoring DPIA",
    description: "Approve the data-protection impact assessment required before browser lockdown or live proctoring may run (ODL-04).",
    risk: "high",
    requiresMfa: true,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:evaluation:read",
    module: "lms",
    resource: "evaluation",
    action: "read",
    label: "Read course evaluation reports",
    description: "View suppressed, cohort-safe course evaluation and outcome/engagement reports by delivery mode (ODL-05).",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "lms:evidence:grant",
    module: "lms",
    resource: "evidence",
    action: "grant",
    label: "Grant accreditation evidence access",
    description: "Grant a time-bounded, scoped, read-only evidence window to an accreditation reviewer (ODL-06).",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "content:page:draft",
    module: "content",
    resource: "page",
    action: "draft",
    label: "Draft public content",
    description: "Write and stage pages, news and events.",
    risk: "low",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
  {
    id: "content:page:publish",
    module: "content",
    resource: "page",
    action: "publish",
    label: "Publish public content",
    description: "Release staged content to the public website.",
    risk: "elevated",
    requiresMfa: false,
    maxGrantDimension: "institution",
  },
];

const byId = new Map(permissionCatalogue.map((entry) => [entry.id, entry]));

export function getPermission(id: string): PermissionDefinition | undefined {
  return byId.get(id);
}

export function requirePermission(id: string): PermissionDefinition {
  const permission = byId.get(id);
  if (!permission) throw new Error(`Unknown permission: ${id}`);
  return permission;
}

export function permissionsByModule(): Map<string, PermissionDefinition[]> {
  const grouped = new Map<string, PermissionDefinition[]>();
  for (const permission of permissionCatalogue) {
    const list = grouped.get(permission.module) ?? [];
    list.push(permission);
    grouped.set(permission.module, list);
  }
  return grouped;
}
