"use client";

import { useState } from "react";
import { AlertTriangle, Check, CheckCircle2, Flag, History, RotateCcw, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@tau/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@tau/ui/dialog";
import { Input } from "@tau/ui/input";
import { Label } from "@tau/ui/label";
import { NativeSelect } from "@tau/ui/native-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@tau/ui/table";
import { PageHeader } from "@/components/console/page-header";
import { ConfigurationStatusBadge, DemoNotice, FilterPanel, TableFrame } from "@/features/configuration/components";
import { useConfiguration } from "@/features/configuration/configuration-store";
import type { FeatureFlag } from "@/features/configuration/types";

export default function FeatureFlagsPage() {
  const { flags, toggleFlag, promoteFlag, rollbackFlag } = useConfiguration();
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<FeatureFlag | null>(null); const [step, setStep] = useState(0); const [target, setTarget] = useState<"Staging" | "Production">("Staging"); const [reason, setReason] = useState(""); const [reviewer, setReviewer] = useState("Amina Yusuf"); const [historyFlag, setHistoryFlag] = useState<FeatureFlag | null>(null);
  const visible = flags.filter((flag) => `${flag.name} ${flag.key} ${flag.owner}`.toLowerCase().includes(query.toLowerCase()));
  const steps = ["Route", "Changes", "Validation", "Reason", "Reviewer", "Confirm"];

  function openPromotion(flag: FeatureFlag) { setSelected(flag); setTarget(flag.staging ? "Production" : "Staging"); setReason(""); setReviewer("Amina Yusuf"); setStep(0); }
  function complete() { if (!selected) return; if (reason.trim().length < 10) { toast.error("Add a meaningful promotion reason."); setStep(3); return; } promoteFlag(selected.id, target, reason, reviewer); toast.success(`${selected.name} promoted to ${target}.`); setSelected(null); }
  function rollback(flag: FeatureFlag, environment: "Staging" | "Production") { rollbackFlag(flag.id, environment, "Rollback to the last known-good configuration"); toast.warning(`${flag.name} rolled back in ${environment}.`); }

  return <>
    <PageHeader eyebrow="CFG-05" title="Feature flags and promotion" description="Review, validate, promote and reverse frontend configuration across development, staging and production." />
    <DemoNotice>Environment changes are simulated in local browser state. Production confirmation never touches a deployment or database.</DemoNotice>
    <FilterPanel><div className="relative min-w-60 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search feature, key or owner" /></div><div className="flex gap-3 text-xs text-muted-foreground"><span>{flags.filter((flag) => flag.development).length} dev</span><span>{flags.filter((flag) => flag.staging).length} staging</span><span>{flags.filter((flag) => flag.production).length} production</span></div></FilterPanel>
    <TableFrame footer="Production cannot be toggled directly; it requires the reviewed promotion workflow."><Table className="min-w-[1160px]"><TableHeader><TableRow><TableHead>Feature</TableHead><TableHead>Owner</TableHead><TableHead>Development</TableHead><TableHead>Staging</TableHead><TableHead>Production</TableHead><TableHead>Audience</TableHead><TableHead>Risk</TableHead><TableHead>Last changed</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map((flag) => <TableRow key={flag.id}><TableCell><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Flag className="size-4" /></span><div><p className="font-semibold">{flag.name}</p><code className="mt-1 block text-xs text-muted-foreground">{flag.key}</code><p className="mt-1 max-w-sm text-xs text-muted-foreground">{flag.description}</p></div></div></TableCell><TableCell>{flag.owner}</TableCell><TableCell><EnvironmentToggle checked={flag.development} label={`${flag.name} in development`} onChange={() => toggleFlag(flag.id, "Development")} /></TableCell><TableCell><EnvironmentToggle checked={flag.staging} label={`${flag.name} in staging`} onChange={() => toggleFlag(flag.id, "Staging")} /></TableCell><TableCell><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold ${flag.production ? "bg-emerald-100 text-emerald-800" : "bg-muted text-muted-foreground"}`}><span className={`size-2 rounded-full ${flag.production ? "bg-emerald-600" : "bg-muted-foreground"}`} />{flag.production ? "On" : "Off"}</span></TableCell><TableCell>{flag.audience}</TableCell><TableCell><ConfigurationStatusBadge status={flag.risk} /></TableCell><TableCell>{flag.lastChanged}</TableCell><TableCell><div className="flex gap-2"><Button size="sm" onClick={() => openPromotion(flag)}>Promote</Button><Button size="iconSm" variant="outline" onClick={() => setHistoryFlag(flag)} aria-label={`View ${flag.name} history`}><History /></Button>{flag.production ? <Button size="iconSm" variant="outline" onClick={() => rollback(flag, "Production")} aria-label={`Roll back ${flag.name}`}><RotateCcw /></Button> : null}</div></TableCell></TableRow>)}</TableBody></Table></TableFrame>

    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Promote {selected?.name}</DialogTitle><DialogDescription>Reviewed, validated and reversible environment promotion.</DialogDescription></DialogHeader><ol className="grid grid-cols-3 gap-2 sm:grid-cols-6">{steps.map((label, index) => <li key={label} className="text-center"><span className={`mx-auto grid size-8 place-items-center rounded-full border text-xs font-bold ${index <= step ? "border-primary bg-primary text-white" : "border-border text-muted-foreground"}`}>{index < step ? <Check className="size-4" /> : index + 1}</span><span className="mt-1 hidden text-[0.62rem] text-muted-foreground sm:block">{label}</span></li>)}</ol><div className="min-h-52 rounded-xl border border-border bg-muted/20 p-5">
      {step === 0 ? <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Source</Label><Input value={target === "Staging" ? "Development" : "Staging"} disabled /></div><div className="space-y-2"><Label htmlFor="promotion-target">Target</Label><NativeSelect id="promotion-target" value={target} onChange={(event) => setTarget(event.target.value as "Staging" | "Production")}><option>Staging</option><option>Production</option></NativeSelect></div></div> : null}
      {step === 1 ? <div><h3 className="font-semibold">Configuration change</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-muted-foreground">Feature</dt><dd className="mt-1">{selected?.name}</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">State</dt><dd className="mt-1">Disabled → Enabled</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">Audience</dt><dd className="mt-1">{selected?.audience}</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">Restrictions</dt><dd className="mt-1">{selected?.restrictions}</dd></div></dl></div> : null}
      {step === 2 ? <div className="space-y-3">{["Dependencies available", "Required review present", "Configuration complete", "No conflicting flags", "Rollback snapshot available"].map((check) => <p key={check} className="flex gap-2 text-sm"><CheckCircle2 className="size-5 text-emerald-600" />{check}</p>)}</div> : null}
      {step === 3 ? <div className="space-y-2"><Label htmlFor="promotion-reason">Change reason</Label><Input id="promotion-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Why is this ready to promote?" /></div> : null}
      {step === 4 ? <div className="space-y-2"><Label htmlFor="promotion-reviewer">Reviewer</Label><NativeSelect id="promotion-reviewer" value={reviewer} onChange={(event) => setReviewer(event.target.value)}><option>Amina Yusuf</option><option>Ngozi Madu</option><option>Adaeze Nwosu</option></NativeSelect><p className="text-sm text-muted-foreground">Reviewer differs from the acting configuration administrator.</p></div> : null}
      {step === 5 ? <div className="space-y-4"><div className="flex gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck className="size-5" />All simulated promotion checks passed.</div>{target === "Production" ? <div className="flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle className="size-5 shrink-0" /><p><strong>Production confirmation.</strong> The feature becomes visible to {selected?.audience}. A rollback snapshot is retained.</p></div> : null}<p className="text-sm"><strong>Reason:</strong> {reason || "Not yet provided"}</p><p className="text-sm"><strong>Reviewer:</strong> {reviewer}</p></div> : null}
    </div><DialogFooter><Button variant="ghost" onClick={() => step === 0 ? setSelected(null) : setStep((value) => value - 1)}>{step === 0 ? "Cancel" : "Back"}</Button>{step < 5 ? <Button onClick={() => setStep((value) => value + 1)}>Continue</Button> : <Button onClick={complete}>Confirm promotion</Button>}</DialogFooter></DialogContent></Dialog>

    <Dialog open={Boolean(historyFlag)} onOpenChange={(open) => !open && setHistoryFlag(null)}><DialogContent><DialogHeader><DialogTitle>{historyFlag?.name} history</DialogTitle><DialogDescription>{historyFlag?.key} · dependencies and retained changes</DialogDescription></DialogHeader><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-muted-foreground">Owner</dt><dd className="mt-1">{historyFlag?.owner}</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">Risk</dt><dd className="mt-1">{historyFlag?.risk}</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">Restrictions</dt><dd className="mt-1">{historyFlag?.restrictions}</dd></div><div><dt className="text-xs font-bold uppercase text-muted-foreground">Dependencies</dt><dd className="mt-1">{historyFlag?.dependencies.join(", ") || "None"}</dd></div></dl><div className="space-y-4 border-l border-border pl-5">{historyFlag?.history.map((entry) => <div key={entry.version}><strong>{entry.changedBy}</strong><p className="text-sm">{entry.reason}</p><p className="text-xs text-muted-foreground">{entry.changedAt}</p></div>)}</div></DialogContent></Dialog>
  </>;
}

function EnvironmentToggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: () => void }) {
  return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={`relative h-6 w-11 rounded-full transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${checked ? "bg-primary" : "bg-muted-foreground/30"}`}><span className={`absolute top-1 size-4 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`} /></button>;
}
