export const siteConfig = {
  name: "Nnamdi Azikiwe University",
  shortName: "NAU",
  officialName: "Nnamdi Azikiwe University",
  tagline: "Discipline · Self Reliance · Excellence",
  description:
    "Nnamdi Azikiwe University is a federal university in Awka, Anambra State, Nigeria.",
  url: "https://www.unizik.edu.ng",
  location: {
    town: "Awka",
    state: "Anambra State",
    country: "Nigeria",
    address: "Nnamdi Azikiwe University, Awka, Anambra State, Nigeria",
  },
  contact: {
    phone: "+234 816 495 8768",
    phoneAlt: "09068856856",
    email: "registrar@unizik.edu.ng",
    emailAlt: "support@unizik.edu.ng",
    admissionsEmail: "registrar@unizik.edu.ng",
  },
  stats: [
    { value: 19, suffix: "", label: "Faculties" },
    { value: 49000, suffix: "+", label: "Students" },
    { value: 3850, suffix: "+", label: "Staff" },
    { value: 135, suffix: "", label: "Accredited Programmes" },
  ],
} as const;

export const route = {
  home: "/",
  about: {
    overview: "/about",
    history: "/about/history",
    mission: "/about/mission-vision",
    leadership: "/leadership",
    governance: "/about/governance",
    accreditations: "/about/accreditations",
    campusMap: "/about/campus-map",
    campuses: "/campuses",
    facilities: "/facilities",
    diversity: "/about/diversity",
    sustainability: "/about/sustainability",
  },
  study: {
    undergraduate: "/undergraduate-programs",
    postgraduate: "/postgraduate",
    faculties: "/faculties",
    departments: "/departments",
    admissions: "/admissions",
    tuition: "/tuition",
    international: "/international",
    studentLife: "/student-life",
  },
  research: {
    overview: "/research",
    centres: "/research/centres",
    publications: "/research/publications",
    funding: "/research/funding",
    innovation: "/research/innovation",
    ethics: "/research/ethics",
  },
  community: {
    news: "/news",
    events: "/events",
    alumni: "/alumni",
    careers: "/careers",
    library: "/library",
    giving: "/giving",
  },
  contact: "/contact",
  login: "/login",
  apply: "/admissions/apply",
} as const;
