"use client";

import { useMemo, useState } from "react";
import { Activity, Search } from "lucide-react";
import { Button } from "@tau/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@tau/ui/dialog";
import { Input } from "@tau/ui/input";
import { NativeSelect } from "@tau/ui/native-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@tau/ui/table";
import { PageHeader } from "@/components/console/page-header";
import { Field } from "@/components/console/section";
import { ConfigurationStatusBadge, DemoNotice, FilterPanel, TableFrame } from "@/features/configuration/components";
import { useConfiguration } from "@/features/configuration/configuration-store";
import type { ConfigurationActivity } from "@/features/configuration/types";

export default function ConfigurationActivityPage() {
  const { activities } = useConfiguration();
  const [query, setQuery] = useState(""); const [module, setModule] = useState("All"); const [status, setStatus] = useState("All"); const [environment, setEnvironment] = useState("All"); const [selected, setSelected] = useState<ConfigurationActivity | null>(null);
  const visible = useMemo(() => activities.filter((activity) => `${activity.actor} ${activity.action} ${activity.record} ${activity.reason}`.toLowerCase().includes(query.toLowerCase()) && (module === "All" || activity.module === module) && (status === "All" || activity.status === status) && (environment === "All" || activity.environment === environment)), [activities, query, module, status, environment]);
  return <>
    <PageHeader eyebrow="EP-02 evidence" title="Configuration activity" description="A readable frontend record of organisation, calendar, vocabulary, rule and promotion changes." />
    <DemoNotice>This page presents Epic 2 mock audit information; it is not the platform’s immutable audit implementation.</DemoNotice>
    <FilterPanel><div className="relative min-w-60 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search actor, action, record or reason" /></div><NativeSelect className="w-full md:w-48" value={module} onChange={(event) => setModule(event.target.value)}><option>All</option>{[...new Set(activities.map((activity) => activity.module))].map((value) => <option key={value}>{value}</option>)}</NativeSelect><NativeSelect className="w-full md:w-40" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option>{[...new Set(activities.map((activity) => activity.status))].map((value) => <option key={value}>{value}</option>)}</NativeSelect><NativeSelect className="w-full md:w-40" value={environment} onChange={(event) => setEnvironment(event.target.value)}><option>All</option>{[...new Set(activities.map((activity) => activity.environment))].map((value) => <option key={value}>{value}</option>)}</NativeSelect><Input type="date" className="w-full md:w-auto" aria-label="Activity start date" defaultValue="2026-09-01" /></FilterPanel>
    <TableFrame footer={`${visible.length} activity records · select a row for before-and-after details`}><Table className="min-w-[1280px]"><TableHeader><TableRow><TableHead>Date and time</TableHead><TableHead>Actor</TableHead><TableHead>Module</TableHead><TableHead>Action</TableHead><TableHead>Record</TableHead><TableHead>Previous value</TableHead><TableHead>New value</TableHead><TableHead>Reason</TableHead><TableHead>Environment</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{visible.map((activity) => <TableRow key={activity.id} className="cursor-pointer" onClick={() => setSelected(activity)}><TableCell className="whitespace-nowrap">{activity.date}</TableCell><TableCell className="font-semibold">{activity.actor}</TableCell><TableCell>{activity.module}</TableCell><TableCell>{activity.action}</TableCell><TableCell>{activity.record}</TableCell><TableCell className="max-w-48 text-muted-foreground">{activity.previous}</TableCell><TableCell className="max-w-48">{activity.next}</TableCell><TableCell className="max-w-56 text-muted-foreground">{activity.reason}</TableCell><TableCell>{activity.environment}</TableCell><TableCell><ConfigurationStatusBadge status={activity.status} /></TableCell><TableCell><Button size="sm" variant="outline" onClick={(event) => { event.stopPropagation(); setSelected(activity); }}>Details</Button></TableCell></TableRow>)}</TableBody></Table></TableFrame>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><Activity className="size-5 text-primary" />{selected?.action}</DialogTitle><DialogDescription>{selected?.record} · {selected?.date}</DialogDescription></DialogHeader><dl className="grid gap-5 sm:grid-cols-2"><Field label="Actor">{selected?.actor}</Field><Field label="Module">{selected?.module}</Field><Field label="Environment">{selected?.environment}</Field><Field label="Status">{selected ? <ConfigurationStatusBadge status={selected.status} /> : null}</Field></dl><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-border bg-muted/30 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Before</p><p className="mt-3 text-sm">{selected?.previous}</p></div><div className="rounded-lg border border-primary/25 bg-primary/5 p-4"><p className="text-xs font-bold uppercase tracking-wide text-primary">After</p><p className="mt-3 text-sm">{selected?.next}</p></div></div><div className="rounded-lg border border-border p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Reason</p><p className="mt-2 text-sm">{selected?.reason}</p></div></DialogContent></Dialog>
  </>;
}
