"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, LockKeyhole, ShieldAlert } from "lucide-react";
import { inventoryForRule } from "@tau/admissions";
import { useAdmissions } from "@tau/admissions";
import { usePerson } from "@tau/identity/react";
import { Badge } from "@tau/ui/badge";
import { PageHeader } from "@/components/console/page-header";
import { Section } from "@/components/console/section";
import { useSession } from "@/providers/session-provider";

export default function AdmissionsCompliancePage() {
  const { scoringRules, admissionDecisionHistory, rankingOverrideAudits } = useAdmissions();
  const { session } = useSession();
  const { data: person, isLoading, isError } = usePerson(session?.personId ?? "");
  const [ruleId, setRuleId] = useState(scoringRules[0]?.id ?? "");
  const [selectedDecisionId, setSelectedDecisionId] = useState(admissionDecisionHistory[0]?.id ?? "");
  const canScore = person?.permissionIds.includes("admissions:screening:score") ?? false;
  const canAudit = person?.permissionIds.includes("identity:audit:read") ?? false;
  const rule = scoringRules.find((item) => item.id === ruleId) ?? scoringRules[0];
  const inventory = useMemo(() => rule ? inventoryForRule(rule) : [], [rule]);
  const selectedDecision = admissionDecisionHistory.find((item) => item.id === selectedDecisionId) ?? admissionDecisionHistory[0];

  if (isLoading) return <div className="rounded-xl border bg-card p-8 text-sm text-muted-foreground" role="status">Loading admissions compliance workspace…</div>;

  return <div className="space-y-6"><Link href="/admissions/screening" className="inline-flex items-center text-sm font-semibold text-muted-foreground hover:text-primary"><ArrowLeft className="mr-1.5 size-4" />Back to screening workspace</Link><PageHeader eyebrow="EP-06 · SCR-08" title="Admissions compliance and decision audit" description="Review admissions decisions and supporting records." actions={<Badge className="border-gold-light/40 bg-navy text-gold-light">Review preview</Badge>} />{isError && <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm" role="alert">Permission details are unavailable. Restricted values remain hidden.</div>}<div className="rounded-xl border border-gold-light/30 bg-navy p-4 text-sm text-white"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-gold-light" /><div><strong>Policy boundary.</strong><p className="mt-1 text-white/70">This is a frontend checklist and integration view. Backend policy enforcement and authoritative audit remain the source of truth.</p></div></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><Section title="Policy input inventory" description="Restricted input values are never rendered to scorers."><div className="mb-4"><label className="text-sm font-medium">Eligibility/scoring model<select className="mt-1 flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={rule?.id ?? ""} onChange={(event) => setRuleId(event.target.value)} aria-label="Eligibility scoring model">{scoringRules.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.version}</option>)}</select></label></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="py-2 pr-3">Input</th><th className="py-2 pr-3">Source</th><th className="py-2 pr-3">Permitted use</th><th className="py-2 pr-3">Scoring usage</th><th className="py-2">Status</th></tr></thead><tbody className="divide-y">{inventory.map((item) => <tr key={item.key}><td className="py-3 pr-3"><div className="font-semibold">{item.name}</div><div className="font-mono text-xs text-muted-foreground">{item.key}</div></td><td className="py-3 pr-3">{item.source}</td><td className="py-3 pr-3">{item.permittedUse === "Restricted_Input" ? <span className="inline-flex items-center gap-1 text-muted-foreground"><LockKeyhole className="size-3.5" />Restricted from scoring</span> : item.permittedUse.replaceAll("_", " ")}</td><td className="py-3 pr-3 text-xs text-muted-foreground">{item.permittedUse === "Restricted_Input" ? "Value hidden" : item.scoringUsage}</td><td className="py-3"><Badge variant={item.status === "Active" ? "success" : "muted"}>{item.status}</Badge></td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-muted-foreground">Rule version: <span className="font-mono">{rule?.version ?? "—"}</span> · Status: {rule?.status ?? "—"}</p></Section>
      <Section title="Compliance checklist" description="Frontend integration states for the selected decision history."><div className="space-y-3">{selectedDecision ? selectedDecision.compliance.map((item) => <div key={item.id} className="flex items-start gap-2 rounded-lg border p-3 text-sm">{item.status === "Complete" ? <CheckCircle2 className="mt-0.5 size-4 text-emerald-600" /> : item.status === "Blocked" ? <ShieldAlert className="mt-0.5 size-4 text-destructive" /> : <span className="mt-1 size-2 rounded-full bg-amber-500" aria-hidden />}<div><div className="font-semibold">{item.label}</div><div className="text-xs text-muted-foreground">{item.detail}</div></div><Badge className="ml-auto" variant={item.status === "Complete" ? "success" : item.status === "Blocked" ? "destructive" : "warning"}>{item.status.replaceAll("_", " ")}</Badge></div>) : <p className="text-sm text-muted-foreground">No decision history is available.</p>}</div></Section></div>
    <Section title="Decision history" description="Automated results are explicitly separated from officer review and head approval."><div className="space-y-3">{admissionDecisionHistory.map((decision) => <button key={decision.id} type="button" onClick={() => setSelectedDecisionId(decision.id)} className={`w-full rounded-lg border p-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selectedDecision?.id === decision.id ? "border-primary bg-primary/5" : "hover:bg-muted/30"}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="font-semibold">{decision.candidateName} · {decision.applicationNumber}</div><div className="mt-1 text-xs text-muted-foreground">Decision: {decision.decision.replaceAll("_", " ")} · Rule {decision.ruleVersion} · Score {decision.score ?? "—"}</div><div className="mt-2 flex flex-wrap gap-2">{decision.humanReview.map((event) => <Badge key={event.stage} variant={event.status === "Complete" ? "success" : "warning"}>{event.stage.replaceAll("_", " ")}{event.actor ? ` · ${event.actor}` : ""}</Badge>)}</div></div><time className="text-xs text-muted-foreground" dateTime={decision.timestamp}>{new Date(decision.timestamp).toLocaleString()}</time></div><div className="mt-3 text-sm text-muted-foreground">{decision.reason}</div><div className="mt-3 text-xs"><span className="font-semibold text-foreground">Inputs used:</span> {decision.inputsUsed.join(", ") || "None"}</div>{decision.override && <div className="mt-3 rounded-md border border-gold-light/30 bg-gold-light/10 p-2 text-xs"><strong>Override:</strong> {decision.override.originalResult.replaceAll("_", " ")} → {decision.override.overriddenResult.replaceAll("_", " ")} · {decision.override.reason} · authority {decision.override.authority}</div>}</button>)}</div></Section>
    <Section title="Override history" description="Existing ranking overrides are shown as frontend audit representations. Authoritative backend audit remains pending.">{rankingOverrideAudits.length === 0 ? <p className="text-sm text-muted-foreground">No ranking overrides recorded.</p> : <div className="divide-y">{rankingOverrideAudits.map((audit) => <div key={audit.id} className="grid gap-2 py-3 sm:grid-cols-[1fr_1fr_auto]"><div><div className="font-semibold">{audit.originalResult.replaceAll("_", " ")} → {audit.overriddenResult.replaceAll("_", " ")}</div><div className="text-xs text-muted-foreground">{audit.reason}</div></div><div className="text-sm">Authority: {audit.authority}<br /><span className="text-xs text-muted-foreground">Reviewer: {audit.actor}</span></div><time className="text-right text-xs text-muted-foreground" dateTime={audit.timestamp}>{new Date(audit.timestamp).toLocaleString()}</time></div>)}</div>}{!canAudit && <p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><LockKeyhole className="size-3.5" />Full institutional audit access requires the existing audit permission.</p>}</Section>
    {!canScore && <div className="text-xs text-muted-foreground">Scoring restrictions are active for this session. Protected values are not available.</div>}
  </div>;
}